# Generated by Django 4.1.3 on 2022-11-16 14:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('title', models.TextField()),
                ('summary', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='media/')),
                ('body', ckeditor.fields.RichTextField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
